version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/frontend
    command: streamlit run feedback_app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
